


- name: copy catalogue service to system directory # here i am using copy module to copy the catalogue.service file from ansible control node to ansible managed node
  ansible.builtin.template: # we should keep templeat 
    src: catalogue.service.j2 # here i am copying the catalogue.service file from ansible control node
    dest: /etc/systemd/system/catalogue.service # here i am copying the catalogue.service file from ansible control node to ansible managed node

- name: systemctl daemon-reload # here i am using command module to run the command systemctl daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable catalogue service # here i am using service module to start and enable the catalogue service
  ansible.builtin.service:
    name: catalogue
    state: restarted # even app is not running you can restart 
    enabled: yes
